site:
  title: Test playbook
  # Antora generates the 404 page and sitemap files only when the `url` property is set.
  url: https://guyharperday.github.io/antora-build/
  start_page: test-antora-site::index.adoc
output:
  clean: true
  dir: ./docs
content:
  sources:
    - url: https://github.com/GuyHarperDay/antora-source.git
      branches: main, another-branch
      edit_url: '{web_url}/tree/{refname}/{path}'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  output_dir: assets
  supplemental_files: ./supplemental-ui
runtime:
  cache_dir: ./.cache/antora
